version: "3"

services:

    webserver1:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./myproject:/var/www/html
        networks:
            - default
            
            
    product-service:
        build: ./product
        ports:
            - 5001:80
        volumes:
            - ./product:/usr/src/app
        
        
    website:
        image: php:apache
        volumes:
            - ./website:/var/www/html
        ports:
            - 5002:80
        depends_on:
            - product-service