1. What is Dockerfile
2. How to create Dockerfile
3. How to build image from Dockerfile
4. Basic Commands

TIPS & TRICKS

Dockerfile : 
A text file with instructions to build image.
It is an automation of Docker Image Creation

FROM
RUN
RUN apt-get update && \
	apt-get upgrade && \
	apt-get install vim
RUN apt-get update upgrade vim curl wget
CMD


Step 1 : Create a file named Dockerfile

Step 2 : Add instructions in Dockerfile

Step 3 : Build dockerfile to create image

Step 4 : Run image to create container



COMMANDS:
docker build 
docker build -t ImageName:Tag directoryOfDocekrfile
docker run image
docker images --filter "dangling=true"

Removing only dangling images:
docker rmi (docker images -q --filter "dangling=true")
docker rmi $(docker images | grep "<none>")

Removing only untagged images (ones with no labels, or with label with no tag):
docker rmi $(docker images -a | grep "^<none>")

Removing unused Docker images:
docker image prune

Removing all images:
docker system prune --all --filter "until=24h"
docker system prune -a


References:
https://github.com/wsargent/docker-cheat-sheet#dockerfile
https://docs.docker.com/engine/reference/builder/#environment-replacement

https://www.google.com/search?q=dockerfile&rlz=1C5CHFA_enIN734IN734&source=lnms&tbm=isch&sa=X&ved=0ahUKEwicqqOe_oTcAhWLbysKHX_6B5sQ_AUICigB&biw=1280&bih=703#imgrc=zY4gTeVpM446JM:

