# from base image ubuntu
From ubuntu
MAINTAINER Bablu Ahmed <bablukpik@gmail.com>

RUN apt-get update

CMD ["echo", "Hello World! from my first docker image"]


# docker build . - for building an image
# docker build -t imageName:tagName 'Location of Dockerfile' - here -t or --tag is name:tag format
